import javax.swing.*;
import java.awt.*;

public class Pictures extends JFrame {
    public JLabel ai_pics;
    public JLabel ai_pics2;
    public JLabel ai_pics3;
    public JLabel ai_pics4;
    public JButton show;
    public JButton back;
    public JButton hide;
    public JLabel pics;
    public JPanel pane;

    Pictures(){
        ImageIcon icon = new ImageIcon("images\\APIC.png");//APIC logo
        ImageIcon samurai = new ImageIcon("images\\Pictures\\Samurai.png");//Generated by AI
        ImageIcon auto = new ImageIcon("images\\Pictures\\auto.png");//Also generated by AI
        ImageIcon sea = new ImageIcon("images\\Pictures\\Sea.png");//The same applies here
        ImageIcon bandit = new ImageIcon("images\\Pictures\\Bandit.png");//And here

        ai_pics = new JLabel();
        ai_pics.setIcon(samurai);
        ai_pics.setBounds(110,120,300,300);
        ai_pics.setVisible(false);

        ai_pics2 = new JLabel();
        ai_pics2.setIcon(auto);
        ai_pics2.setBounds(560,120,300,300);
        ai_pics2.setVisible(false);

        ai_pics3 = new JLabel();
        ai_pics3.setIcon(sea);
        ai_pics3.setBounds(110,450,300,300);
        ai_pics3.setVisible(false);

        ai_pics4 = new JLabel();
        ai_pics4.setIcon(bandit);
        ai_pics4.setBounds(560,450,300,300);
        ai_pics4.setVisible(false);


        show = new JButton("Show");
        show.setBounds(50,800,250,100);
        show.setFont(new Font("Flaky",Font.PLAIN,20));
        show.setIcon(icon);
        show.setBackground(new Color(20,20,100));
        show.setForeground(new Color(240,230,255));
        show.setFocusable(false);
        show.addActionListener(e -> ai_pics.setVisible(true));
        show.addActionListener(e -> ai_pics2.setVisible(true));
        show.addActionListener(e -> ai_pics3.setVisible(true));
        show.addActionListener(e -> ai_pics4.setVisible(true));

        /*
        *The button above functions as the button which shows the pictures generated by AI
        * The button bellow functions as the button which hides the pictures generated by the AI
        * This was done to make a special effect to the application
        * The lines responsible are from 50 to 53 and 69 to 72
         */

        hide = new JButton("Hide");
        hide.setBounds(365,800,250,100);
        hide.setFont(new Font("Flaky",Font.PLAIN,20));
        hide.setIcon(icon);
        hide.setBackground(new Color(20,20,100));
        hide.setForeground(new Color(240,230,255));
        hide.setFocusable(false);
        hide.addActionListener(e -> ai_pics.setVisible(false));
        hide.addActionListener(e -> ai_pics2.setVisible(false));
        hide.addActionListener(e -> ai_pics3.setVisible(false));
        hide.addActionListener(e -> ai_pics4.setVisible(false));

        back = new JButton("Back");
        back.setBounds(675,800,250,100);
        back.setFont(new Font("Flaky",Font.PLAIN,20));
        back.setIcon(icon);
        back.setBackground(new Color(20,20,100));
        back.setForeground(new Color(240,230,255));
        back.setFocusable(false);
        back.addActionListener(e -> new Welcome());
        back.addActionListener(e -> this.dispose());


        pics = new JLabel("Cool Pictures");
        pics.setFont(new Font("Flaky",Font.PLAIN,40));
        pics.setForeground(new Color(240,230,255));

        pane = new JPanel();
        pane.setBounds(0,0,1000,70);
        pane.setBackground((new Color(20,20,100)));
        pane.add(pics);

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("APIC");
        this.getContentPane().setBackground(new Color(30,78,150));
        this.setSize(new Dimension(1000,1000));
        this.setIconImage(icon.getImage());
        this.setResizable(false);
        this.add(ai_pics);
        this.add(ai_pics2);
        this.add(ai_pics3);
        this.add(ai_pics4);
        this.add(pane);
        this.add(show);
        this.add(hide);
        this.add(back);
        this.setLocation(500,10);
        this.setLayout(null);
        this.setVisible(true);
    }
}
